// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.Models;

namespace TicketSystem.Migrations
{
    [DbContext(typeof(TicketContext))]
    partial class TicketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketSystem.Models.Point", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PointId");

                    b.ToTable("Points");

                    b.HasData(
                        new
                        {
                            PointId = 1,
                            Name = "1 Point"
                        },
                        new
                        {
                            PointId = 2,
                            Name = "2 Points"
                        },
                        new
                        {
                            PointId = 3,
                            Name = "3 Points"
                        },
                        new
                        {
                            PointId = 5,
                            Name = "5 Points"
                        },
                        new
                        {
                            PointId = 8,
                            Name = "8 Points"
                        },
                        new
                        {
                            PointId = 13,
                            Name = "13 Points"
                        },
                        new
                        {
                            PointId = 21,
                            Name = "21 Points"
                        });
                });

            modelBuilder.Entity("TicketSystem.Models.Sprint", b =>
                {
                    b.Property<string>("SprintId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SprintNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SprintId");

                    b.ToTable("Sprints");

                    b.HasData(
                        new
                        {
                            SprintId = "1",
                            SprintNumber = "Sprint 1"
                        },
                        new
                        {
                            SprintId = "2",
                            SprintNumber = "Sprint 2"
                        },
                        new
                        {
                            SprintId = "3",
                            SprintNumber = "Sprint 3"
                        },
                        new
                        {
                            SprintId = "4",
                            SprintNumber = "Sprint 4"
                        },
                        new
                        {
                            SprintId = "5",
                            SprintNumber = "Sprint 5"
                        },
                        new
                        {
                            SprintId = "6",
                            SprintNumber = "Sprint 6"
                        },
                        new
                        {
                            SprintId = "7",
                            SprintNumber = "Sprint 7"
                        },
                        new
                        {
                            SprintId = "8",
                            SprintNumber = "Sprint 8"
                        },
                        new
                        {
                            SprintId = "9",
                            SprintNumber = "Sprint 9"
                        });
                });

            modelBuilder.Entity("TicketSystem.Models.Status", b =>
                {
                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = "1",
                            Name = "To Do"
                        },
                        new
                        {
                            StatusId = "2",
                            Name = "In Progress"
                        },
                        new
                        {
                            StatusId = "3",
                            Name = "Quality Assurance"
                        },
                        new
                        {
                            StatusId = "4",
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("TicketSystem.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.Property<string>("SprintId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TicketId");

                    b.HasIndex("PointId");

                    b.HasIndex("SprintId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketSystem.Models.Ticket", b =>
                {
                    b.HasOne("TicketSystem.Models.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSystem.Models.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
